export const clerkAppearance = {
  layout: {
    logoPlacement: "inside" as const,
    socialButtonsPlacement: "bottom" as const,
    shimmer: false,
  },
  variables: {
    colorPrimary: "hsl(247 100% 68%)",
    colorDanger: "hsl(0 84% 60%)",
    colorSuccess: "hsl(142 71% 45%)",
    colorBackground: "hsl(222 47% 8%)",
    colorInputBackground: "hsl(217 33% 14%)",
    colorInputText: "hsl(210 40% 98%)",
    colorText: "hsl(210 40% 98%)",
    colorTextSecondary: "hsl(215 20% 65%)",
    colorNeutral: "hsl(217 33% 17%)",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-heebo), system-ui, sans-serif",
    fontSize: "0.9375rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: [
      "bg-card/95 backdrop-blur-xl border border-border/80 shadow-2xl shadow-primary/10",
      "rounded-2xl w-full",
    ].join(" "),
    header: "gap-2",
    headerTitle: "text-xl font-bold text-foreground",
    headerSubtitle: "text-sm text-muted-foreground",
    logoBox: "hidden",
    socialButtonsBlockButton: [
      "border border-border bg-muted/50 text-foreground",
      "hover:bg-muted transition-colors",
    ].join(" "),
    dividerLine: "bg-border",
    dividerText: "text-muted-foreground text-xs",
    formFieldLabel: "text-foreground text-sm font-medium",
    formFieldInput: [
      "bg-muted/80 border-border text-foreground",
      "focus:ring-2 focus:ring-primary/40 focus:border-primary",
    ].join(" "),
    formButtonPrimary: [
      "bg-primary hover:bg-primary/90 text-primary-foreground",
      "font-semibold shadow-lg shadow-primary/20 transition-all",
    ].join(" "),
    footerActionLink: "text-primary hover:text-primary/80 font-medium",
    footerActionText: "text-muted-foreground",
    identityPreviewText: "text-foreground",
    identityPreviewEditButton: "text-primary",
    formResendCodeLink: "text-primary",
    otpCodeFieldInput: "border-border bg-muted/80 text-foreground",
    alertText: "text-sm",
    navbar: "hidden",
    footer: "bg-transparent",
  },
};
